---
id: "minion-01"
location: "my-location"

karaf:
  shell:
    ssh:
      host: "0.0.0.0"

ipc:
  rpc:
    kafka:
      bootstrap.servers: "kafka:9092"
      acks: 1

  sink:
    kafka:
      bootstrap.servers: "kafka:9092"
      acks: 1

  twin:
    kafka:
      bootstrap.servers: "kafka:9092"
      acks: 1

netmgt:
  syslog:
    syslog.listen.interface: "0.0.0.0"
    syslog.listen.port: 1514

  traps:
    trapd.listen.interface: "0.0.0.0"
    trapd.listen.port: 1162
